# Generated by Django 4.2.5 on 2023-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photographer",
            name="image",
            field=models.FileField(max_length=500, null=True, upload_to=""),
        ),
    ]
