# Generated by Django 4.2.5 on 2023-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_photographer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photographer",
            name="image",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(max_length=500, upload_to=""),
        ),
    ]
