# Generated by Django 4.2.5 on 2023-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_photographer_image_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date",
        ),
        migrations.AddField(
            model_name="post",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post-image-uploads"),
        ),
    ]
