# Generated by Django 4.2.5 on 2023-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_post_date_post_order_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="num_likes",
            field=models.IntegerField(default=0),
        ),
    ]
