# Generated by Django 4.2.5 on 2023-10-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_comment_num_likes_post_num_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photographer",
            name="image",
        ),
    ]
